---
title: "Numerical EDA"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
library(dplyr)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

Load the weather data as well.

```{r}
data("weather_df")

weather_df = 
  weather_df |> 
  mutate(
    month = lubridate::floor_date(date, unit = "month")
  )
```

Now we have everything we need!

```{r}
weather_df |> 
  filter(prcp > 0) |> 
  ggplot(aes(x = prcp)) +
  geom_histogram()
```

```{r}
weather_df |> 
  filter(prcp > 1000)
```

```{r}
weather_df |>
  ggplot(aes(x = tmax, y = tmin, color = name, shape = name)) +
  geom_point()
```

now group_by()

```{r}
weather_df |> 
  group_by(name, month)
```


summarize

```{r}
weather_df |> 
  group_by(name, month) |> 
  summarize(count=n())
```

```{r}
weather_df |> 
  count(name, month)
```

```{r}
weather_df |> 
  group_by(month) |> 
  summarize(
    count=n(), 
    n_days = n_distinct(date)
    )
```

dont do !!!!!

```{r}
weather_df |> 
  pull(tmax) |> 
  summary()
```

do this 
```{r}
weather_df |> 
  group_by(name) |> 
  summarize(
    mean_tmax = mean(tmax, na.rm = TRUE),
    median_tmax = median(tmax, na.rm = TRUE),
    sd_prcp = sd(prcp, na.rm = TRUE),
    q25_prcp = quantile(prcp, 0.25, na.rm = TRUE),
    q95_prcp = quantile(prcp, 0.95, na.rm = TRUE)
  ) |> 
  knitr::kable(digits = 2)
```

^^^ knit a nice table

```{r}
weather_df |> 
  group_by(name, month) |> 
  summarize(
    mean_tmax = mean(tmax, na.rm = TRUE)
  ) |> 
  pivot_wider(
    names_from = name, 
    values_from = mean_tmax
  ) |> 
  knitr::kable(digits = 2)
```

visualize
```{r}
weather_df |> 
  group_by(name, month) |> 
  summarize(
    mean_tmax = mean(tmax, na.rm = TRUE)
  ) |> 
  ggplot(aes(x = month, y = mean_tmax, color = name)) +
  geom_point() +
  geom_line()
```

```{r}
weather_df |> 
  group_by(name) |> 
  mutate(center_tmax = tmax - mean(tmax, na.rm = TRUE)) |> 
  ggplot(aes(x = date, y = center_tmax, color = name)) +
  geom_point()
```

what about window functions -- ranking things

```{r}
weather_df |> 
  group_by(name, month) |> 
  mutate(temp_rank = min_rank(desc(tmax))) |> 
  filter(temp_rank < 2)
```

lead and lag

```{r}
weather_df |> 
  group_by(name) |> 
  mutate(
    lagged_tmax = lag(tmax, 3), 
    lead_tmax = lead(tmax)
    )
```

```{r}
weather_df |> 
  group_by(name) |> 
  mutate(
    lagged_tmax = lag(tmax), 
    temp_change = tmax - lagged_tmax
    ) |> 
  summarise(
    mean_temp_change = mean(temp_change, na.rm = TRUE),
    sd_temp_change = sd(temp_change, na.rm = TRUE)
  )
```

revisit some examples

```{r}
pulse_df = 
  haven::read_sas("data/public_pulse_data.sas7bdat copy") |> 
  janitor::clean_names() |> 
  pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to = "visit", 
    names_prefix = "bdi_score_",
    values_to = "bdi") |>
  mutate(
    visit = replace(visit, visit == "bl", "00m"),
    visit = factor(visit)) |> 
  select(id, visit, bdi, everything())

pulse_df |> 
  group_by(visit) |> 
  summarize(
    mean_bdi = mean(bdi, na.rm = TRUE), 
    median_bdi = median(bdi, na.rm = TRUE)
  ) |> 
  knitr::kable(digits = 2)
```

FAS data

```{r}
pups_df = 
  read_csv("data/FAS_pups.csv", skip = 3, na = c("", ".", "NA")) |> 
  janitor::clean_names() 

litters_df = 
  read_csv("data/FAS_litters.csv", na = c("", ".", "NA")) |> 
  janitor::clean_names() |> 
  separate(group, into = c("dose", "day_of_tx"), 3)

fas_df =
  left_join(pups_df, litters_df, by = "litter_number") |> 
  select(litter_number, dose, day_of_tx, everything())

fas_df |> 
  group_by(dose, day_of_tx) |> 
  summarise(
    mean_ears = mean(pd_ears, an.rm = TRUE)
  ) |> 
  pivot_wider(
    names_from = day_of_tx, 
    values_from = mean_ears
  )

```



